# Generated by Django 5.1.6 on 2025-02-16 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_userfile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
