# Generated by Django 5.1.6 on 2025-02-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_alter_userfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
